FROM fedora:rawhide

ENV container docker

RUN dnf -y update \
  && dnf --allowerasing install systemd systemd-libs dbus \
  && dnf clean all

RUN systemctl mask dev-mqueue.mount dev-hugepages.mount \
    systemd-remount-fs.service sys-kernel-config.mount \
    sys-kernel-debug.mount sys-fs-fuse-connections.mount \
    display-manager.service graphical.target systemd-logind.service

#ADD dbus.service /etc/systemd/system/dbus.service
#RUN systemctl enable dbus.service

# https://vpavlin.eu/2015/02/fedora-docker-and-systemd/
VOLUME ["/run", "/tmp"]

RUN cp /usr/lib/systemd/system/dbus.service /etc/systemd/system/; \
  sed -i 's/OOMScoreAdjust=-900//' /etc/systemd/system/dbus.service


ADD ./wrapdocker /usr/local/bin/wrapdocker
RUN chmod +x /usr/local/bin/wrapdocker

# for debugging
RUN dnf -y update && dnf install -y procps-ng && dnf clean all

# docker
ENV DOCKER_VERSION 1.8.1
RUN curl -SL -o /usr/local/bin/docker https://get.docker.com/builds/Linux/x86_64/docker-$DOCKER_VERSION

COPY docker-storage /etc/sysconfig/
COPY docker.* /etc/systemd/system/
RUN systemctl enable docker.service

# fleet
ENV FLEET_VERSION v0.11.5
RUN curl -SL https://github.com/coreos/fleet/releases/download/$FLEET_VERSION/fleet-$FLEET_VERSION-linux-amd64.tar.gz \
  | tar -xz --directory /usr/local/bin

COPY fleet.* /etc/systemd/system/
RUN systemctl enable fleet.service

# etcd
ENV ETCD_VERSION v2.1.2
RUN curl -SL https://github.com/coreos/etcd/releases/download/$ETCD_VERSION/etcd-$ETCD_VERSION-linux-amd64.tar.gz \
  | tar -xz --directory /usr/local/bin

COPY etcd2.* /etc/systemd/system/
RUN systemctl enable etcd2.service

RUN chmod +x /usr/local/bin/*



CMD ["wrapdocker"]

# docker build -f Dockerfile_fedora_rawhide --rm -t local/systemd-docker-rawhide .
# docker run --privileged -d -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v $PWD:/units local/systemd-docker-rawhide
# docker exec -ti [..] bash
